# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a00f5f61c9b462e3581598a3bc3fe3815bfb49c4385296a8e7b34c83b3fa39bc2b9461c5875c0e361a3132f42b66b56cf877f30e6477eca043d1261809d8d146

test:
  secret_key_base: c9ab05788e839d79ecccd98eca6516308e5cae56b266b2f85b9a173909226ee506b9f5c2ccc89cea6c8e5f2e690159475a3dbf381472f1213e5cfe05057ada43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
